<?php

require_once __DIR__.'/../autoload.php';

use Nrk\Fluent\Monolog\FluentHandler;

// Start fluentd on the local host using the sample configuration file
// that can be generated by calling fluentd with the -s option.

$log = new Monolog\Logger('debug.monolog');

$log->pushHandler(new FluentHandler('http://127.0.0.1'));
$log->pushHandler(new FluentHandler('tcp://127.0.0.1'));

$log->addError("OH NOES!!11!1!");
